//! README generation templates

use handlebars::Handlebars;
use serde::Serialize;
use thiserror::Error;

use crate::resources::ResourceKind;

/// Template errors
#[derive(Debug, Error)]
pub enum TemplateError {
    #[error("Template error: {0}")]
    Render(#[from] handlebars::RenderError),
    #[error("Template registration error: {0}")]
    Registration(#[from] Box<handlebars::TemplateError>),
}

/// Template context for main README
#[derive(Debug, Serialize)]
pub struct ProjectContext {
    pub name: String,
    pub description: Option<String>,
    pub service_name: String,
    pub resource_counts: Vec<ResourceCount>,
    pub generated_at: String,
}

#[derive(Debug, Serialize)]
pub struct ResourceCount {
    pub kind: String,
    pub directory: String,
    pub count: usize,
}

/// Template context for resource-type README
#[derive(Debug, Serialize)]
pub struct ResourceTypeContext {
    pub kind: String,
    pub kind_plural: String,
    pub resources: Vec<ResourceSummary>,
    pub description: String,
}

#[derive(Debug, Serialize)]
pub struct ResourceSummary {
    pub name: String,
    pub description: Option<String>,
    pub dependencies: Vec<String>,
}

/// README generator
pub struct ReadmeGenerator {
    handlebars: Handlebars<'static>,
}

impl ReadmeGenerator {
    pub fn new() -> Result<Self, TemplateError> {
        let mut handlebars = Handlebars::new();
        handlebars.set_strict_mode(true);

        // Register templates
        handlebars
            .register_template_string("project", PROJECT_README_TEMPLATE)
            .map_err(Box::new)?;
        handlebars
            .register_template_string("resource_type", RESOURCE_TYPE_README_TEMPLATE)
            .map_err(Box::new)?;

        Ok(Self { handlebars })
    }

    /// Generate main project README
    pub fn generate_project_readme(&self, ctx: &ProjectContext) -> Result<String, TemplateError> {
        Ok(self.handlebars.render("project", ctx)?)
    }

    /// Generate resource-type README
    pub fn generate_resource_readme(
        &self,
        ctx: &ResourceTypeContext,
    ) -> Result<String, TemplateError> {
        Ok(self.handlebars.render("resource_type", ctx)?)
    }
}

impl Default for ReadmeGenerator {
    fn default() -> Self {
        Self::new().expect("Failed to create ReadmeGenerator")
    }
}

/// Get description for a resource kind
pub fn resource_kind_description(kind: ResourceKind) -> &'static str {
    match kind {
        ResourceKind::Index => {
            "Indexes define the schema for searchable content, including fields, analyzers, and scoring profiles."
        }
        ResourceKind::Indexer => {
            "Indexers automate data ingestion from supported data sources into search indexes."
        }
        ResourceKind::DataSource => {
            "Data sources define connections to external data stores for indexer ingestion."
        }
        ResourceKind::Skillset => {
            "Skillsets define AI enrichment pipelines that process content during indexing."
        }
        ResourceKind::SynonymMap => {
            "Synonym maps define equivalent terms to improve search relevance."
        }
        ResourceKind::KnowledgeBase => {
            "Knowledge bases (preview) provide structured knowledge for AI agent interactions."
        }
        ResourceKind::KnowledgeSource => {
            "Knowledge sources (preview) connect indexes to knowledge bases for agentic search."
        }
    }
}

const PROJECT_README_TEMPLATE: &str = r#"# {{name}}

{{#if description}}
{{description}}

{{/if}}
Azure AI Search configuration managed by [hoist](https://github.com/mklab-se/hoist).

## Service

- **Service name**: `{{service_name}}`

## Resources

| Type | Directory | Count |
|------|-----------|-------|
{{#each resource_counts}}
| {{kind}} | [`{{directory}}/`](./{{directory}}/) | {{count}} |
{{/each}}

## Usage

```bash
# Pull latest configuration from Azure
hoist pull

# Show differences between local and remote
hoist diff

# Push local changes to Azure
hoist push --dry-run
hoist push
```

---

*Generated by hoist on {{generated_at}}*
"#;

const RESOURCE_TYPE_README_TEMPLATE: &str = r#"# {{kind_plural}}

{{description}}

## Resources

{{#each resources}}
### {{name}}

{{#if description}}
{{description}}

{{/if}}
{{#if dependencies}}
**Dependencies:**
{{#each dependencies}}
- {{this}}
{{/each}}
{{/if}}

{{/each}}
"#;
